version: 0.2

env:
  variables:
    EXIT_CODE: 0
    REPO: codepipeline-testing
    CREDSTASH_KEY: test-key

phases:
  install:
    commands:
      - echo "installing -- stub"
  pre_build:
    commands:
      - echo testing env
      - env
      - echo "building docker image"
      - docker build -t $REPO:build .
  build:
    commands:
      - echo building
      - echo "src version -- $CODEBUILD_SOURCE_VERSION"
      - docker run --rm $REPO:$CODEBUILD_SOURCE_VERSION
  post_build:
    commands:
      - echo "post_build -- stub"
# artifacts:
#   files:
#     - location
#     - location
#   discard-paths: yes
#   base-directory: location
# cache:
#   paths:
#     - '/root/.m2/**/*'
