version: 0.2

env:
  variables:
    EXIT_CODE: 0
    REPO: codepipeline-testing
    CREDSTASH_KEY: test-key

phases:
  install:
    commands:
      - echo "bootstrapping env..."
      - export DOCKERFILE_HASH=$(md5sum Dockerfile | awk '{print $1}')
      - export IMAGE=$REPO:$DOCKERFILE_HASH
      # can attempt to fetch docker image here, otherwise build
      - echo "building docker image $IMAGE"
      - docker build -t $IMAGE .
  pre_build:
    commands:
      - cd $CODEBUILD_SRC_DIR
  build:
    commands:
      - echo building
      - echo "src version -- $CODEBUILD_SOURCE_VERSION"
      - docker run --rm $IMAGE /bin/bash -c "git status && git remote -v && git branch"
  post_build:
    commands:
      - echo "post_build -- stub"
# artifacts:
#   files:
#     - location
#     - location
#   discard-paths: yes
#   base-directory: location
# cache:
#   paths:
#     - '/root/.m2/**/*'
