version: 0.2

env:
  variables:
    EXIT_CODE: 0
    CREDSTASH_KEY: test-key
  # parameter-store:
  #   key: "value"
  #   key: "value"
            
phases:
  install:
    commands:
      - echo "installing -- stub"
  pre_build:
    commands:
      - echo "pre_build -- stub"
  build:
    commands:
      - echo building
      - echo "src version -- $CODEBUILD_SOURCE_VERSION"
      - ./build.sh
      - pip install -r requirements.txt
      - python test.py
      - exit $EXIT_CODE
  post_build:
    commands:
      - echo "post_build -- stub"
# artifacts:
#   files:
#     - location
#     - location
#   discard-paths: yes
#   base-directory: location
# cache:
#   paths:
#     - '/root/.m2/**/*'
